name: ftk
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

publish_to: none
# Add regular dependencies here.
dependencies:
  nanoid: ^1.0.0
  ssr:
    git:
      url: git@github.com:Haupti/dart-ssr.git
      ref: de095de33796f1bdf4224b7a29a5d48bf55b037e # commit hash


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
